server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: containers
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: containerlogs
#           __path__: /var/lib/docker/containers/*/*-json.log  # Specify JSON logs

# scrape_configs:
# - job_name: system
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: varlogs
#       __path__: /var/log/*log
#

# scrape_configs:
#   - job_name: docker
#     pipeline_stages:
#       - docker: {}
#     static_configs:
#       - labels:
#           job: docker
#           __path__: /var/lib/docker/containers/*/*-json.log

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_label_traefik_enable]
        regex: "true"
        action: keep

    # pipeline_stages:
    #   - docker: {}
    # relabel_configs:
    #   # Extract proper container name
    #   - source_labels: [__meta_docker_container_name]
    #     regex: '/(.+)'
    #     target_label: container_name
    #     replacement: '$1'

    #   # Assign a job label to traefik containers
    #   - source_labels: [__meta_docker_container_name]
    #     regex: '/?traefik.*'
    #     target_label: job
    #     replacement: traefik

    #   # Only scrape containers with traefik.enable=true
    #   - source_labels: [__meta_docker_container_label_traefik_enable]
    #     action: keep
    #     regex: true
